trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  buildConfiguration: 'Release'

steps:
- task: DotNetCoreCLI@2
  displayName: 'Restore $(buildConfiguration)'
  inputs:
    command: 'restore'
    projects: '**/Appliction/*.csproj'
    feedsToUse: 'select'
    vstsFeed: 'my-pipeline-feed'

- task: DotNetCoreCLI@2
  displayName: 'Build $(buildConfiguration)'
  inputs:
    command: 'build'
    projects: '**/Appliction/*.csproj'
    arguments: '--configuration $(buildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: 'Test $(buildConfiguration)'
  inputs:
    command: 'test'
    projects: '**/WebTest/*.csproj'
    arguments: '--configuration $(buildConfiguration) --collect "Code coverage"'

- task: DotNetCoreCLI@2
  displayName: 'Publish $(buildConfiguration)'
  inputs:
    command: 'publish'
    projects: '**/Appliction/*.csproj'
    publishWebProjects: True
    arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)'
    zipAfterPublish: True